spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  info:
    git:
      mode: simple
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.bank.customerservice: INFO
    org.springframework.security: INFO
